services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: orders_db
      POSTGRES_USER: orders_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/  # Используем том

volumes:  # Объявляем том в корневом разделе
  postgres_data: